#
# Bastien's customization for powerlevel9k theme
#

# Activate double line prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true


#
# Left prompt customization
#

# Left prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv context dir_writable dir vcs)

# Fix icon issues with Konsole terminal
POWERLEVEL9K_HOME_ICON=$'\uf015 '
POWERLEVEL9K_HOME_SUB_ICON=$'\uf115 '
POWERLEVEL9K_OK_ICON=$'\uf00c '
POWERLEVEL9K_FOLDER_ICON=$'\uf114 '
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='015'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='160'

POWERLEVEL9K_VIRTUALENV_BACKGROUND='040'

POWERLEVEL9K_CONTEXT_TEMPLATE=$'%n\uf1fa%m \uf0f4 '
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='038'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='232'

POWERLEVEL9K_DIR_HOME_BACKGROUND='220'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='220'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='220'


#
# Right prompt customization
#

# Right prompt elements
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time time)

POWERLEVEL9K_TIME_BACKGROUND='245'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

